version: "2"

networks:
  test:

services:
  offchaindb:
    container_name: offchaindb
    image: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - 5990:5984
    hostname: offchaindb
    networks:
      - test
      
  # offchain_mongodb:
  #   image: mongo:latest
  #   container_name: "mongodb"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #     - MONGODB_USER="admin" 
  #     - MONGODB_PASS="password"
  #   volumes:
  #     - ./data/db:/data/db
  #   ports:
  #       - 27017:27017
  #   command: mongod --smallfiles --logpath=/dev/null # --quiet